---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8snginxtest
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/Albroy/k8s_nginx_test.git
